//
//  DeveloperPreview.swift
//  AirBnB
//
//  Created by Lavkush kumar on 13/07/24.
//

import Foundation

class DeveloperPreview{
    static let shared = DeveloperPreview()
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            imageURL:["listing-1","listing-2","listing-3","listing-4","listing-5"],
            address: "124 Main St",
            city: "Miami",
            state: "Florida",
            title: "Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundary,.tv],
            type: .villa
        ),
        
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "John Smith",
                ownerImageUrl: "male-1",
                numberOfBedrooms: 2,
                numberOfBathrooms: 1,
                numberOfGuests: 4,
                numberOfBeds: 3,
                pricePerNight: 100,
                latitude: 37.7749,
                longitude: -122.4194,
                imageURL:["listing-2","listing-3","listing-4","listing-5","listing-6"],
                address: "123 Main St",
                city: "San Francisco",
                state: "CA",
                title: "Cozy Apartment near Downtown",
                rating: 4.5,
                features: [.selfCheckIn, .superHost],
                amenities: [.wifi, .kitchen, .tv, .laundary, .alarmSystem],
                type: .apartment
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Jane Miller",
                ownerImageUrl: "female-2",
                numberOfBedrooms: 3,
                numberOfBathrooms: 2,
                numberOfGuests: 6,
                numberOfBeds: 4,
                pricePerNight: 150,
                latitude: 34.0522,
                longitude: -118.2437,
                imageURL:["listing-3","listing-4","listing-5","listing-6","listing-7"],
                address: "456 Oak St",
                city: "Los Angeles",
                state: "CA",
                title: "Spacious House with Garden",
                rating: 5.0,
                features: [.superHost],
                amenities: [.pool, .kitchen, .wifi, .tv, .laundary],
                type: .house
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Emily Johnson",
                ownerImageUrl: "female-1",
                numberOfBedrooms: 2,
                numberOfBathrooms: 1,
                numberOfGuests: 3,
                numberOfBeds: 2,
                pricePerNight: 120,
                latitude: 40.7128,
                longitude: -74.0060,
                imageURL:["listing-4","listing-5","listing-6","listing-7","listing-8"],
                address: "789 Elm St",
                city: "New York",
                state: "NY",
                title: "Modern Townhouse in the Heart of the City",
                rating: 4.2,
                features: [.selfCheckIn],
                amenities: [.wifi, .office, .balcony, .kitchen, .alarmSystem],
                type: .townHouse
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Michael Brown",
                ownerImageUrl: "male-2",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 8,
                numberOfBeds: 5,
                pricePerNight: 300,
                latitude: 33.6844,
                longitude: -117.8265,
                imageURL:["listing-5","listing-6","listing-7","listing-8","listing-9"],
                address: "101 Palm Ave",
                city: "Newport Beach",
                state: "CA",
                title: "Luxurious Villa with Ocean View",
                rating: 4.8,
                features: [.superHost],
                amenities: [.pool, .kitchen, .wifi, .tv, .alarmSystem],
                type: .villa
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Chris Anderson",
                ownerImageUrl: "male-3",
                numberOfBedrooms: 2,
                numberOfBathrooms: 1,
                numberOfGuests: 4,
                numberOfBeds: 2,
                pricePerNight: 130,
                latitude: 41.8781,
                longitude: -87.6298,
                imageURL:["listing-6","listing-7","listing-8","listing-9","listing-10"],
                address: "456 Maple St",
                city: "Chicago",
                state: "IL",
                title: "Charming Cottage with Garden",
                rating: 4.6,
                features: [.selfCheckIn],
                amenities: [.kitchen, .wifi, .tv, .laundary],
                type: .house
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Sophie Miller",
                ownerImageUrl: "female-3",
                numberOfBedrooms: 1,
                numberOfBathrooms: 1,
                numberOfGuests: 2,
                numberOfBeds: 1,
                pricePerNight: 90,
                latitude: 37.3382,
                longitude: -121.8863,
                imageURL:["listing-7","listing-8","listing-9","listing-10"],
                address: "789 Oak St",
                city: "San Jose",
                state: "CA",
                title: "Sunny Apartment with Panoramic Views",
                rating: 4.9,
                features: [.superHost],
                amenities: [.wifi, .kitchen, .tv],
                type: .apartment
            ),
            .init(
                id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "David Clark",
                ownerImageUrl: "male-4",
                numberOfBedrooms: 3,
                numberOfBathrooms: 2,
                numberOfGuests: 6,
                numberOfBeds: 3,
                pricePerNight: 180,
                latitude: 39.5501,
                longitude: -105.7821,
                imageURL:["listing-8","listing-9","listing-10"],
                address: "234 Pine St",
                city: "Denver",
                state: "CO",
                title: "Rustic Cabin Retreat in the Mountains",
                rating: 4.7,
                features: [.selfCheckIn, .superHost],
                amenities: [.kitchen, .wifi, .tv, .laundary, .balcony],
                type: .house
            )
    ]
}
